apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-etcd
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /volume5/nfs1/openshift/etcd
    server: 192.168.1.14
  persistentVolumeReclaimPolicy: Delete
