apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logging
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /volume5/nfs1/openshift/logging
    server: 192.168.1.14
  persistentVolumeReclaimPolicy: Delete
