apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /volume5/nfs1/openshift/prometheus
    server: 192.168.1.14
  persistentVolumeReclaimPolicy: Delete
