apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alert2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /volume5/nfs1/openshift/prometheusalert2
    server: 192.168.1.14
  persistentVolumeReclaimPolicy: Delete
